#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SUBMISSION_URL = "https://userlab.utk.edu/courses/cosc466/datalab/submit";
$AUTOGRADE_TIMEOUT = 0;
1;
